version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: app
    volumes:
      - mongodb_data:/data/db
      - ./initDb.js:/docker-entrypoint-initdb.d/initDb.js:ro

volumes:
  mongodb_data: